
version: '3.8'

services:
  mp-spdz:
    image: mp-spdz
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
      args:
        machine: malicious-shamir-party.x
        prep_dir: /opt/preprocessing-data
        ssl_dir: /opt/ssl
        cryptoplayers: 3
        gfp_mod_sz: 4
        compile_options: "-v -C --field=256"
        src: tutorial
    platform: "linux/amd64"
    environment:
      PREP_DIR: ${PREP_DIR}
      PRIME: ${PRIME}
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Utils:/usr/src/MP-SPDZ/Utils
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
      - ./Networking:/usr/src/MP-SPDZ/Networking
      - ./Machines:/usr/src/MP-SPDZ/Machines
      - ./Protocols:/usr/src/MP-SPDZ/Protocols
      - ./Processor:/usr/src/MP-SPDZ/Processor
      - ./Math:/usr/src/MP-SPDZ/Math
      - ./Tools:/usr/src/MP-SPDZ/Tools
      - ./logs:/usr/src/MP-SPDZ/logs
      - ./latency-control.sh:/usr/src/MP-SPDZ/latency-control.sh
      - ./test/:/usr/src/MP-SPDZ/test/
    command: tail -F anything
