version: '3.8'

services:
  mp-spdz:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
      - ./Scripts/hbswap:/go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
      - ./Scripts/hbswap/poa:/opt/hbswap/poa
      - ./Utils/random-shamir.cpp:/usr/src/MP-SPDZ/Utils/random-shamir.cpp
