version: '3.8'

services:

  eth.chain:
    image: ethereum/client-go:latest
    working_dir: /usr/src/
    volumes:
      - ./Scripts/hbswap/scripts/chain.sh:/usr/src/Scripts/hbswap/scripts/chain.sh
      - ./Scripts/hbswap/poa:/usr/src/Scripts/hbswap/poa
      - ./Scripts/hbswap/poa/keystore/account_0:/usr/src/Scripts/hbswap/poa/keystore/account_0
    entrypoint: ""
    command: sh Scripts/hbswap/scripts/chain.sh

  contract-deployer:
    image: hbswap-go
    build:
      context: .
      dockerfile: Scripts/hbswap/contract-deployer.Dockerfile
    working_dir: /go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap/go
    volumes:
      - ./Scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./Scripts/hbswap:/go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    depends_on:
      - eth.chain
    entrypoint: ""
    command: ["wait-for-it", "eth.chain:8545", "--", "go", "run", "deploy/deploy.go", "eth.chain"]

  mpc:
    image: hbswap-mpc
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
      - ./Scripts/hbswap:/gopath/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    command: echo "UNDER CONSTRUCTION!"
