version: '3.8'

services:
  public.deposit:
    image: hbswap-go
    build:
      context: .
      dockerfile: contract.Dockerfile
      target: client
    networks:
      - hbswap
    working_dir: /go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    volumes:
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - .:/go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    entrypoint: ""
    # TODO wait for contract to be deployed/available
    command: ["bash", "scripts/client-public-deposit.sh", "eth.chain"]

  secret.deposit:
    image: hbswap-go
    build:
      context: .
      dockerfile: contract.Dockerfile
      target: client
    networks:
      - hbswap
    working_dir: /go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    volumes:
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - .:/go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    entrypoint: ""
    # TODO wait for contract to be deployed/available
    command: ["bash", "scripts/client-secret-deposit.sh", "eth.chain"]

  trade:
    image: hbswap-mpc
    build:
      context: ../..
      dockerfile: hbswap.Dockerfile
      target: hbswap
    networks:
      - hbswap
    volumes:
      - ./scripts/trade.sh:/usr/src/MP-SPDZ/trade.sh
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - .:/usr/src/MP-SPDZ/Scripts/hbswap
      - .:/go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    working_dir: /usr/src/MP-SPDZ
    command: ["wait-for-it", "mpc.node.3:8080", "--", "bash", "trade.sh", "eth.chain"]
    #command: ["wait-for-it", "mpc.node.3:8080", "--", "bash", "trade.sh", "eth.chain", "0", "1.1", "-2.5"]
    #command: ["wait-for-it", "mpc.node.3:8080", "--", "bash", "trade.sh", "eth.chain", "0", "-1.1", "2"]
