# MPC network configuation

# MPC network params
n = 4
t = 1

# MPC servers
[[servers]]
id = 0
host = "mpc.nodes"
http_port = 8080

[[servers]]
id = 1
host = "mpc.nodes"
http_port = 8081

[[servers]]
id = 2
host = "mpc.nodes"
http_port = 8082

[[servers]]
id = 3
host = "mpc.nodes"
http_port = 8083
