# MPC network configuation

# MPC network params
n = 4
t = 1

# MPC servers
[[servers]]
id = 0
host = "127.0.0.1"
http_port = 8080
http_host = "0.0.0.0"

[[servers]]
id = 1
host = "127.0.0.1"
http_port = 8081
http_host = "0.0.0.0"

[[servers]]
id = 2
host = "127.0.0.1"
http_port = 8082
http_host = "0.0.0.0"

[[servers]]
id = 3
host = "127.0.0.1"
http_port = 8083
http_host = "0.0.0.0"
